### PR TITLE
Removing defdelegate from `FunWithFlags.Actor` protocol

### LINKED ISSUE #104: defdelegate not supported inside protocols
FunWithFlags is using `defdelegate` within a `defprotocol` block, which is not officially supported and will break in a future Elixir release. See: https://github.com/elixir-lang/elixir/issues/10877#issuecomment-813266478

### PR DESCRIPTION
**Pull request by kelvinst**
Fixes #104

### CODE REVIEW

**Comment by tompave** [comment]
Thanks for fixing this 👍

**Comment by marcandre** [comment]
THhanks!
@tompave A release would be appreciated.

**Comment by marcandre** [comment]
@tompave Any chance of a release soon?

**Comment by tompave** [comment]
@marcandre sorry for the wait, here is the release: https://hex.pm/packages/fun_with_flags/1.7.0

**Comment by marcandre** [comment]
Awesome, thanks so much!

**Pull request merged**
