### PR TITLE
Add another case for Redis initialization (again)

### PR DESCRIPTION
**Pull request by iamvery**
Re-opening #147 

Unfortunately it seems the GitHub UI doesn't allow me to re-open that PR. I expected it to update the base once the base branch was merged, but that must not work with forks.

### CODE REVIEW

**Comment by tompave** [comment]
Thank you for this.

**Comment by tompave** [comment]
@iamvery please try the latest master and let me know if this fixes the issue for you.

**Comment by iamvery** [comment]
@tompave I confirmed the code at `50a80851d7ce676b0bfce2f1931d219caaced9b7` works great for our use case. I'm looking forward to the release. Thank you!

**Comment by tompave** [comment]
@iamvery released. Thanks for this work!

**Pull request merged**
