### PR TITLE
Improve error handling for redis store

### PR DESCRIPTION
**Pull request by chubarovNick**

### CODE REVIEW

**Comment by tompave** [comment]
Hello!

Thank you for the PR!

Can you please provide some more info on why you needed these changes? An example of the cases where these errors would happen?

**Comment by tompave** [comment]
I get `%Redix.ConnectionError{}`, but I'd be curious about the `%Redix.Error{}`. If the Redis adapter is sending invalid command to the Redis server, then that's something that should be fixed.

**Comment by tompave** [comment]
Is it something like:

```
set fun_with_flags:foobar just_a_string
```

and then:

```elixir
FunWithFlags.enabled?(:foobar)
** (Protocol.UndefinedError) protocol String.Chars not implemented for %Redix.Error{message: "WRONGTYPE Operation against a key holding the wrong kind of value"} of type Redix.Error (a struct).
```

**Comment by chubarovNick** [comment]
Hello. We face `%Redix.ConnectionError{}` in our project, and then I handle all possible error values from `Redix.command/2`. I think it's almost impossible to get this error with your library :)

**Comment by tompave** [comment]
I see, fair enough.

Thank you for the improvement!

**Pull request merged**
